/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface MenuItem {
        "displayChildren": boolean;
        "item": any;
        "showCheckbox": boolean;
    }
    interface NewComponent {
        "someProp": string;
    }
}
declare global {
    interface HTMLMenuItemElement extends Components.MenuItem, HTMLStencilElement {
    }
    var HTMLMenuItemElement: {
        prototype: HTMLMenuItemElement;
        new (): HTMLMenuItemElement;
    };
    interface HTMLNewComponentElement extends Components.NewComponent, HTMLStencilElement {
    }
    var HTMLNewComponentElement: {
        prototype: HTMLNewComponentElement;
        new (): HTMLNewComponentElement;
    };
    interface HTMLElementTagNameMap {
        "menu-item": HTMLMenuItemElement;
        "new-component": HTMLNewComponentElement;
    }
}
declare namespace LocalJSX {
    interface MenuItem {
        "displayChildren"?: boolean;
        "item"?: any;
        "showCheckbox"?: boolean;
    }
    interface NewComponent {
        "someProp"?: string;
    }
    interface IntrinsicElements {
        "menu-item": MenuItem;
        "new-component": NewComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "menu-item": LocalJSX.MenuItem & JSXBase.HTMLAttributes<HTMLMenuItemElement>;
            "new-component": LocalJSX.NewComponent & JSXBase.HTMLAttributes<HTMLNewComponentElement>;
        }
    }
}
